general:
  delete_after_record: false # Whether to delete local versions of videos after record or not
transaction:
  path_to_robonomics_file: "robonomics" # where lies the binary file, ends with a binary filename
  remote: '--remote wss://earth.rpc.robonomics.network' # e.g. ws://127.0.0.1:9944
camera:
  key: '' # secret key in robonomics network
print_barcode:
  enable: false
print_qr: # Whether to print QR code stickers pointing to a video in IPFS
  enable: false
  logos: false # Enables logo insertion into a qrcode
print_security_tag: # Whether to print seal tags with optional timestamp on them
  enable: false
  enable_timestamp: false
printer: # Info about the Brother Label printer used in your operation
  printer_model: "QL-800"
  paper_width: 50 # paper width in mm
  address: "usb://0x04f9:0x209e" # usually static
yourls: # Information about the yourls node used for short link creation
  server: ''
  username: ''
  password: ''
intro:
  enable: false # If you want to attach an intro video to the main vid. Intro should be placed in media/intro.mp4
pinata:
  enable: true # Enable pinning of files published to IPFS to Pinata
  pinata_api: ""
  pinata_secret_api: ""
ipfs:
  enable: false
  gateway_address: "https://gateway.ipfs.io/ipfs/" # IPFS gateway to use when creating links
datalog:
  enable: true # Whether to write certain data to Robonomics datalog or not
api_server: # socket for the Api server to run on
  ip: "0.0.0.0"
  port: 5000
mongo_db: # MongoDB credentials
  username: your_username
  password: your_password
