name: Deploy in master-k8s
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  Build-and-push-DockerCont:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Install doctl
        uses: digitalocean/action-doctl@v2.1.0
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

      - name: Login in Container Registry Digital Ocean
        run: doctl registry login

      - name: Build Docker Container
        run: docker build ./ -t ${{ secrets.DOREGISTRY}}/feecc-workbench-daemon:master
      
      - name: Tag container for Container Registry Digital Ocean
        run: docker tag ${{ secrets.DOREGISTRY}}/feecc-workbench-daemon:master ${{ secrets.DOREGISTRY}}/feecc-workbench-daemon

      - name: Push container in Container Registry Digital Ocean
        run: docker push ${{ secrets.DOREGISTRY}}/feecc-workbench-daemon:master

  # Push-DockerCont:
  #   needs: [Build-and-push-DockerCont]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2

  #     - name: Install doctl
  #       uses: digitalocean/action-doctl@v2.1.0
  #       with:
  #         token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

  #     - name: Install kubectl
  #       run: sudo apt-get update && sudo apt-get install -y apt-transport-https ca-certificates curl && sudo curl -fsSLo /usr/share/keyrings/kubernetes-archive-keyring.gpg https://packages.cloud.google.com/apt/doc/apt-key.gpg && echo "deb [signed-by=/usr/share/keyrings/kubernetes-archive-keyring.gpg] https://apt.kubernetes.io/ kubernetes-xenial main" | sudo tee /etc/apt/sources.list.d/kubernetes.list && sudo apt-get update && sudo apt-get install -y kubectl

  #     - name: Init Kubectl
  #       run: doctl kubernetes cluster kubeconfig save ${{ secrets.DOINITK8S}} 
      